server:
  port: 8778
spring:
  application:
    name: feign-service
eureka:
  instance:
    hostname: feign-service
  client:
    service-url:
      defaultZone: http://register-master:8760/eureka/

feign:
  hystrix:
    enabled: true

# Feign日志记录只能响应DEBUG日志级别，所以配置
logging:
  level:
    com:
      santeamo:
        api:
          FeignInterface: DEBUG