spring:
  # profile=default
  profiles: default
server:
  port: 8760
eureka:
  instance:
    hostname: register-master
  client:
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    #但是注册中心集群时候必须为true；因为集群时，其他Eureka需要从此Eureka中的节点上获取数据
    register-with-eureka: false
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据，设置为false
    fetch-registry: false
    #设置Eureka的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/